// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "callback_messages.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace net {

namespace {

const ::google::protobuf::Descriptor* NetStartResult_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  NetStartResult_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_callback_5fmessages_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  NetStartResult_descriptor_ = file->message_type(0);
  NetStartResult::default_instance_ = new NetStartResult();
  static const int NetStartResult_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetStartResult, result_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetStartResult, ip_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetStartResult, port_),
  };
  NetStartResult_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      NetStartResult_descriptor_,
      NetStartResult::default_instance_,
      NetStartResult_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetStartResult, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(NetStartResult, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(NetStartResult));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    NetStartResult_descriptor_, NetStartResult::default_instance_);
  NetStartResult::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_callback_5fmessages_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\027callback_messages.proto\022\003net\":\n\016NetSta"
    "rtResult\022\016\n\006result\030\001 \002(\t\022\n\n\002ip\030\002 \001(\t\022\014\n\004"
    "port\030\003 \001(\005", 90,
  &protobuf_BuildDesc_callback_5fmessages_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_callback_5fmessages_2eproto {
  StaticDescriptorInitializer_callback_5fmessages_2eproto() {
    protobuf_BuildDesc_callback_5fmessages_2eproto();
  }
} static_descriptor_initializer_callback_5fmessages_2eproto_;


// ===================================================================

const ::std::string NetStartResult::_default_result_;
const ::std::string NetStartResult::_default_ip_;

NetStartResult::NetStartResult()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    ip_(const_cast< ::std::string*>(&_default_ip_)),
    port_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void NetStartResult::InitAsDefaultInstance() {}

NetStartResult::NetStartResult(const NetStartResult& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    result_(const_cast< ::std::string*>(&_default_result_)),
    ip_(const_cast< ::std::string*>(&_default_ip_)),
    port_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

NetStartResult::~NetStartResult() {
  if (result_ != &_default_result_) {
    delete result_;
  }
  if (ip_ != &_default_ip_) {
    delete ip_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* NetStartResult::descriptor() {
  if (NetStartResult_descriptor_ == NULL) protobuf_BuildDesc_callback_5fmessages_2eproto();
  return NetStartResult_descriptor_;
}

const NetStartResult& NetStartResult::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_callback_5fmessages_2eproto();
  return *default_instance_;
}

NetStartResult* NetStartResult::default_instance_ = NULL;

NetStartResult* NetStartResult::New() const {
  return new NetStartResult;
}

const ::google::protobuf::Descriptor* NetStartResult::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* NetStartResult::GetReflection() const {
  if (NetStartResult_reflection_ == NULL) protobuf_BuildDesc_callback_5fmessages_2eproto();
  return NetStartResult_reflection_;
}

}  // namespace net
