// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "transport_message.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace transport {

namespace {

const ::google::protobuf::Descriptor* TransportMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  TransportMessage_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_transport_5fmessage_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  TransportMessage_descriptor_ = file->message_type(0);
  TransportMessage::default_instance_ = new TransportMessage();
  static const int TransportMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransportMessage, rpc_msg_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransportMessage, hp_msg_),
  };
  TransportMessage_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      TransportMessage_descriptor_,
      TransportMessage::default_instance_,
      TransportMessage_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransportMessage, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(TransportMessage, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      sizeof(TransportMessage));
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    TransportMessage_descriptor_, TransportMessage::default_instance_);
  TransportMessage::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_transport_5fmessage_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  ::transport::protobuf_BuildDesc_hole_5fpuching_5fmessages_2eproto();
  ::rpcprotocol::protobuf_BuildDesc_rpcmessage_2eproto();
  pool->InternalBuildGeneratedFile(
    "\n\027transport_message.proto\022\ttransport\032\033ho"
    "le_puching_messages.proto\032\020rpcmessage.pr"
    "oto\"h\n\020TransportMessage\022(\n\007rpc_msg\030\001 \001(\013"
    "2\027.rpcprotocol.RpcMessage\022*\n\006hp_msg\030\002 \001("
    "\0132\032.transport.HolePunchingMsg", 189,
  &protobuf_BuildDesc_transport_5fmessage_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_transport_5fmessage_2eproto {
  StaticDescriptorInitializer_transport_5fmessage_2eproto() {
    protobuf_BuildDesc_transport_5fmessage_2eproto();
  }
} static_descriptor_initializer_transport_5fmessage_2eproto_;


// ===================================================================



TransportMessage::TransportMessage()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    rpc_msg_(NULL),
    hp_msg_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void TransportMessage::InitAsDefaultInstance() {  rpc_msg_ = const_cast< ::rpcprotocol::RpcMessage*>(&::rpcprotocol::RpcMessage::default_instance());
  hp_msg_ = const_cast< ::transport::HolePunchingMsg*>(&::transport::HolePunchingMsg::default_instance());
}

TransportMessage::TransportMessage(const TransportMessage& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    rpc_msg_(NULL),
    hp_msg_(NULL) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

TransportMessage::~TransportMessage() {
  if (this != default_instance_) {
    delete rpc_msg_;
    delete hp_msg_;
  }
}

const ::google::protobuf::Descriptor* TransportMessage::descriptor() {
  if (TransportMessage_descriptor_ == NULL) protobuf_BuildDesc_transport_5fmessage_2eproto();
  return TransportMessage_descriptor_;
}

const TransportMessage& TransportMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_transport_5fmessage_2eproto();
  return *default_instance_;
}

TransportMessage* TransportMessage::default_instance_ = NULL;

TransportMessage* TransportMessage::New() const {
  return new TransportMessage;
}

const ::google::protobuf::Descriptor* TransportMessage::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* TransportMessage::GetReflection() const {
  if (TransportMessage_reflection_ == NULL) protobuf_BuildDesc_transport_5fmessage_2eproto();
  return TransportMessage_reflection_;
}

}  // namespace transport
